### ISSUE TITLE
Background transparent

### ISSUE THREAD

**Issue by nicolai-nichitin** [Vitalie-Olexici/Spotify#1]
You need to make background transparent

**Comment by Vitalie-Olexici** [comment]
I made investigation, and observed that the transparent image will not make the text visibile, so we need to work with the current image.

**Comment by nicolai-nichitin** [comment]
Ok, agree

**Comment by Vitalie-Olexici** [comment]
Yep

вс, 20 февр. 2022 г., 01:58 Nicolai Nichitin ***@***.***>:
